// Portions adapted from pdftorevit-agent (https://github.com/BadAstronaut/pdftorevit-agent), MIT, Copyright (c) 2026 Le Phu; based on KenLP/RevitMCPServer.
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.ExtensibleStorage;

namespace RevitMCPCommandSet.Utils
{
    /// <summary>
    /// Stable per-element source key (e.g. "1725-S301/F3/017") stored with Extensible Storage,
    /// so no shared/project parameter is required.
    /// </summary>
    public static class SourceKeyStore
    {
        public static readonly Guid SchemaGuid = new Guid("B3C1E0A4-6F2D-4E8B-9A57-2D4C8E1F7A93");
        public const string SourceKeyField = "SourceKey";
        public const string ManifestHashField = "ManifestHash";
        private const string VendorId = "RevitMCP";

        public static Schema GetOrCreateSchema()
        {
            var existing = Schema.Lookup(SchemaGuid);
            if (existing != null) return existing;
            var builder = new SchemaBuilder(SchemaGuid);
            builder.SetSchemaName("RevitMCPSourceKey");
            builder.SetDocumentation("Stable source key for elements generated by Revit MCP.");
            builder.SetVendorId(VendorId);
            builder.SetReadAccessLevel(AccessLevel.Public);
            builder.SetWriteAccessLevel(AccessLevel.Public);
            builder.AddSimpleField(SourceKeyField, typeof(string));
            builder.AddSimpleField(ManifestHashField, typeof(string));
            return builder.Finish();
        }

        private static string ReadField(Element el, string field)
        {
            var schema = Schema.Lookup(SchemaGuid);
            if (schema == null) return null;
            try
            {
                var entity = el.GetEntity(schema);
                if (entity == null || !entity.IsValid()) return null;
                var v = entity.Get<string>(field);
                return string.IsNullOrEmpty(v) ? null : v;
            }
            catch { return null; }
        }

        public static string Read(Element el) => ReadField(el, SourceKeyField);

        public static string ReadManifestHash(Element el) => ReadField(el, ManifestHashField);

        /// <summary>Must run inside a transaction.</summary>
        public static void Write(Element el, string sourceKey, string manifestHash)
        {
            var entity = new Entity(GetOrCreateSchema());
            entity.Set(SourceKeyField, sourceKey ?? "");
            entity.Set(ManifestHashField, manifestHash ?? "");
            el.SetEntity(entity);
        }

        /// <summary>All elements carrying a source key: key -> elements (id order).</summary>
        public static Dictionary<string, List<Element>> ScanAll(Document doc)
        {
            var map = new Dictionary<string, List<Element>>(StringComparer.Ordinal);
            if (Schema.Lookup(SchemaGuid) == null) return map;
            var elements = new FilteredElementCollector(doc)
                .WherePasses(new ExtensibleStorageFilter(SchemaGuid))
                .ToElements();
            foreach (var e in elements.OrderBy(x => x.Id.GetValue()))
            {
                var key = Read(e);
                if (key == null) continue;
                if (!map.TryGetValue(key, out var list)) map[key] = list = new List<Element>();
                list.Add(e);
            }
            return map;
        }
    }
}
