// Portions adapted from pdftorevit-agent (https://github.com/BadAstronaut/pdftorevit-agent), MIT, Copyright (c) 2026 Le Phu; based on KenLP/RevitMCPServer.
// See THIRD_PARTY_NOTICES.md at the repository root for the full license text.
// NOTE (our MCP): tests THEIR `callBatch`/`get_element_info` contract. Pending an OUR-MCP adapter.
import test from 'node:test';import assert from 'node:assert/strict';import {runPaced,readBatched} from './execution_runner.mjs';
const element=k=>({source_key:k,steps:[{command:'create_wall',params:{}}]});
const setup=()=>{const calls=[],events=[];return {calls,events,args:{elements:[element('a'),element('b')],commit:true,authorized:true,guard:async()=>{},validate:async()=>{},match:async()=>({state:'missing'}),verify:async()=>events.push('verify'),refresh:async()=>events.push('refresh'),invalidateCache:async()=>{},writeEvidence:async()=>{},sleep:async ms=>events.push(ms),callBatch:async(s,stop,dry)=>{calls.push({s,stop,dry});return {ok:true,committed:!dry,results:[{ok:true}]};}}};};
test('paced commits preserve payloads and pause between refreshed checkpoints',async()=>{const {args,calls,events}=setup();const r=await runPaced(args);assert.equal(r.created,2);assert.deepEqual(calls[0].s,calls[1].s);assert.deepEqual(calls[2].s,calls[3].s);assert.deepEqual(events,['verify','refresh',200,'verify','refresh']);});
test('dry-run never commits or sleeps',async()=>{const {args,calls,events}=setup();await runPaced({...args,commit:false});assert(calls.every(x=>x.dry));assert.equal(events.length,0);});
test('failures and cancellation stop subsequent creation',async()=>{const {args}=setup();let n=0;await assert.rejects(runPaced({...args,callBatch:async()=>{n++;return {ok:false};}}));assert.equal(n,1);await assert.rejects(runPaced({...args,signal:{aborted:true}}),/Interrupted/);});
test('identity matches skip; ambiguity and missing authorization reject',async()=>{const {args}=setup();assert.equal((await runPaced({...args,match:async()=>({state:'exact'})})).skipped,2);await assert.rejects(runPaced({...args,authorized:false}));await assert.rejects(runPaced({...args,match:async()=>({state:'ambiguous'})}));});
test('evidence failure prevents commit',async()=>{const {args,calls}=setup();await assert.rejects(runPaced({...args,writeEvidence:async()=>{throw Error('disk');}}));assert.equal(calls.length,0);});
test('batched reads retain order and reject missing/reordered rows',async()=>{assert.deepEqual(await readBatched([2,1],async s=>({ok:true,results:s.map(x=>({ok:true,data:{id:x.params.id}}))})),[{id:2},{id:1}]);await assert.rejects(readBatched([1],async()=>({ok:true,results:[]})));await assert.rejects(readBatched([1,2],async()=>({ok:true,results:[{ok:true,data:{id:2}},{ok:true,data:{id:1}}]})));});
